application.security.jwt.secret-key=NDY4RTRFN0Y5OUQ1NjZCMzYyNTc2NTcwNTg3QTU4NzE0OTdFNjM1MjM2NTQ2RDY3M0QzQTMzNzM5N0U0NzI0NQ==

application.security.jwt.expiration=86400000


spring.datasource.url=jdbc:mysql://91.98.233.27:3307/nebula?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true


spring.datasource.username=root
spring.datasource.password=flatwhite**

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true