CREATE TABLE plans (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    max_instances INT NOT NULL,
    price DECIMAL(10,2) DEFAULT 0.00,
    is_free BOOLEAN DEFAULT FALSE
);

CREATE TABLE users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(120) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    user_type ENUM('INDIVIDUAL', 'ORGANIZATION') DEFAULT 'INDIVIDUAL',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    plan_id BIGINT REFERENCES plans(id)
);

CREATE TABLE individuals (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(120),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE organizations (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    owner_id BIGINT NOT NULL REFERENCES individuals(id),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE organization_members (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    org_id BIGINT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE(org_id, user_id)
);

CREATE TABLE engines (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE containers (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    ip VARCHAR(100) NOT NULL,
    port INT NOT NULL,
    engine_id BIGINT NOT NULL REFERENCES engines(id),
    status ENUM('CREATING', 'RUNNING', 'SUSPENDED', 'DELETED') DEFAULT 'CREATING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_dbs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    db_user VARCHAR(100) NOT NULL,
    db_password_enc VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE instances (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    container_id BIGINT NOT NULL REFERENCES containers(id) ON DELETE CASCADE,
    user_db_id BIGINT NOT NULL REFERENCES user_dbs(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE payments (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    plan_id BIGINT NOT NULL REFERENCES plans(id),
    status ENUM('APPROVED', 'PENDING', 'FAILED', 'PAUSED') DEFAULT 'PENDING',
    transaction_id VARCHAR(100),
    mercado_pago_payment_id VARCHAR(100),
    amount DECIMAL(10,2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE password_rotations (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_db_id BIGINT NOT NULL REFERENCES user_dbs(id) ON DELETE CASCADE,
    old_password_enc VARCHAR(255),
    new_password_enc VARCHAR(255),
    rotated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);